import React from 'react';
import { data } from '../config/data'; 

const ReportComponent = () => {
  const reports = data.reports;

  return (
    <div className="report-container p-4">
      <h2 className="text-2xl font-bold mb-4">REPORTS</h2>
      <div className="grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
        {reports.map((report) => (
          <div key={report.reportId} className="bg-white p-4 rounded-lg shadow-md">
            <h3 className="text-lg font-semibold">{report.title}</h3>
            <p className="text-sm text-gray-500 mb-2">Generated By: {report.generatedBy}</p>
            <p className="text-sm text-gray-500 mb-2">Date: {new Date(report.dateGenerated).toLocaleDateString()}</p>
            <p className="text-sm mb-4">{report.summary}</p>
            <a
              href={report.fileUrl}
              className="text-blue-500 hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              View Report
            </a>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ReportComponent;
